# -*- coding: utf-8 -*-
"""hr_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8w5ik9XBuk0ahR3kpwYklH-pFyTdDKI
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

df = pd.read_csv("employee-attrition (1).csv")
df.head()

df.shape

df.info()

df.isnull().sum()

df = df.dropna()

df = df.drop_duplicates()

total_employees = df.shape[0]
print("Total Employees:", total_employees)

attrition_count = df[df["Attrition"] == "Yes"].shape[0]
print("Employees Left:", attrition_count)

attrition_rate = (attrition_count / total_employees) * 100
print("Attrition Rate: {:.2f}%".format(attrition_rate))

dept_attrition = df.groupby("Department")["Attrition"].value_counts().unstack()
print(dept_attrition)

dept_attrition.plot(kind="bar", stacked=True, figsize=(8,5))
plt.title("Department-wise Attrition")
plt.ylabel("Number of Employees")
plt.show()

sns.boxplot(x="Attrition", y="MonthlyIncome", data=df)
plt.title("Monthly Income vs Attrition")
plt.show()

overtime_attrition = df.groupby("OverTime")["Attrition"].value_counts().unstack()
overtime_attrition.plot(kind="bar", stacked=True, figsize=(6,4))
plt.title("Overtime Impact on Attrition")
plt.show()

sns.histplot(df["Age"], bins=20)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

df.to_csv("HR_Cleaned_Data.csv", index=False)

files.download("HR_Cleaned_Data.csv")

plt.figure()
sns.boxplot(x="Attrition", y="MonthlyIncome", data=df)
plt.savefig("salary_vs_attrition.png")
files.download("salary_vs_attrition.png")